name: Build + Release Wheels

on:
  workflow_dispatch:
    inputs:
      deploy_to_testpypi:
        description: "Whether the build should be deployed to test.pypi.org instead of regular PyPI"
        required: true
        default: false

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            build_command: make vinput.lib
            artifact_name: vinput.lib
            extra_setup: echo "No extra setup needed"
          - os: macos-latest
            build_command: make libvinput.dylib
            artifact_name: libvinput.dylib
            extra_setup: echo "No extra setup needed"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Setup Dependencies
        run: ${{ matrix.extra_setup }}
      - name: Build native binary
        run: |
          ${{ matrix.build_command }}
      - name: Build wheel
        run: |
          pip install build
          python -m build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-${{ matrix.os }}
          path: dist
      - name: Install Twine
        run: pip install twine

      - name: Upload to PyPI
        if: github.event.inputs.deploy_to_testpypi == 'false'
        run: twine upload dist/* --verbose --skip-existing -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
        env:
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/

      - name: Upload to TestPyPI
        if: github.event.inputs.deploy_to_testpypi == 'true'
        run: twine upload dist/* --verbose --skip-existing -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}
        env:
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
